<a href="https://colab.research.google.com/github/IntelliCoder-AI/Notebook-Hands-On-Large-Language-Models/blob/main/NumPy_Fundaments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Array Creation

In [2]:
import numpy as np

In [2]:
# 1D Array
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
# 2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(type(b))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [7]:
# 3D Array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)
print(type(c))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
<class 'numpy.ndarray'>


In [15]:
# Specific datatype (dtype)
float_dtype = np.array([1,2,3,4], dtype = float)
print("Float datatype array :{}".format(float_dtype))

bool_dtype = np.array([0,1,2,0], dtype=bool)
print("Boolean datatype array :{}".format(bool_dtype))

complex_dtype = np.array([1,2,3,4], dtype=complex)
print("Complex datatype array :{}".format(complex_dtype))

Float datatype array :[1. 2. 3. 4.]
Boolean datatype array :[False  True  True False]
Complex datatype array :[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [21]:
# np.arange
arr1 = np.arange(1, 10)
print(arr1)

arr2 = np.arange(10, 21, 2)
print(arr2)

print(arr2.shape)

[1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20]
(6,)


In [23]:
# reshape
arr3 = arr1.reshape(3,3)
print(arr3)

print("\n")
arr4 = arr2.reshape(2,3)
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[10 12 14]
 [16 18 20]]


In [25]:
# np.ones and np.zeros

ones_arr = np.ones((3,3))
print(ones_arr)

print("\n")

zeros_arr = np.zeros((4,3))
print(zeros_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# np.random , random floating-point numbers between 0.0 (inclusive) and 1.0 (exclusive).
random_1d = np.random.random(4)
print("1D Array :{}".format(random_1d))

print("\n")

random_2d = np.random.random((2,3))
print("2D Array : {}".format(random_2d))

print("\n")
random_3d = np.random.random((2,3,3))
print("3D Array :{}".format(random_3d))

1D Array :[0.91810802 0.94839447 0.89964897 0.6855536 ]


2D Array : [[0.64095675 0.13281458 0.21438675]
 [0.48406876 0.45084585 0.25471626]]


3D Array :[[[0.44671923 0.04937226 0.15219727]
  [0.58612742 0.79676952 0.19565549]
  [0.53273306 0.50515584 0.32524519]]

 [[0.36074048 0.54804667 0.82202645]
  [0.29773246 0.67276766 0.83520291]
  [0.75835368 0.29127234 0.16145437]]]


In [33]:
# np.linspace  -> linear Space -> creates an array of evenly spaced numbers between a start and an end value.
lin_space = np.linspace(1,10,5)  #np.linspace(start, end, number of value)
print(lin_space)

[ 1.    3.25  5.5   7.75 10.  ]


### Creates an identity matrix.
An identity matrix is a square matrix where:

All diagonal elements are 1

All other elements are 0

In [34]:
# np.identity
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [12]:
# ndim --> Number of Dimension
a1 = np.arange(1, 5)
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], dtype=float)

print(a1)
print("\n")
print(a2)
print("\n")
print(a3)

[1 2 3 4]


[[1 2 3]
 [4 5 6]]


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [11]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [5]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(2, 3)
(2, 2, 3)


In [6]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

4
6
12


In [14]:
# itemsize  -> memory occupy size based on datatypes
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [13]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
float64


### Changing Datatypes

In [16]:
# astype
a1.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

### Array Operations

In [17]:
arr5 = np.arange(12).reshape(3,4)
arr6 = np.arange(12,24).reshape(3,4)

print(arr5)
print("\n")
print(arr6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [18]:
# Arithematic Operations
print(arr5 + arr6)
print("\n")
print(arr5 - arr6)
print("\n")
print(arr5 * arr6)
print("\n")
print(arr5 / arr6)
print("\n")

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]


[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]




In [20]:
print(arr5 * 2)
print("\n")
print(arr5 + 2)
print("\n")
print(arr5 - 2)
print("\n")
print(arr5 / 2)
print("\n")

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]




In [21]:
print(arr5 % 2)

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [22]:
print(arr5 ** 2)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [24]:
# Relational Operations
print(arr5 > 5)
print("\n")
print(arr5 < 5)
print("\n")
print(arr5 >= 5)
print("\n")
print(arr5 <= 5)
print("\n")
print(arr5 == 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


[[False False False False]
 [False  True False False]
 [False False False False]]


### Array Functions

In [28]:
arr7 = np.random.random((3,3))
arr7 = np.round(arr7*100)
print(arr7)

[[74. 84. 14.]
 [83. 58. 83.]
 [47. 51. 84.]]


In [29]:
# min / max / sum / prod  -- > from the entire array
print(arr7.min())
print(arr7.max())
print(arr7.sum())
print(arr7.prod())

14.0
84.0
578.0
7001168657341824.0


In [31]:
# From a given column (0) or Row (1)
print(np.max(arr7, axis=1))
print(np.max(arr7, axis=0))

[84. 83. 84.]
[83. 84. 84.]


In [34]:
# mean / median / std / var
print(np.mean(arr7))
print(np.mean(arr7, axis=0))

64.22222222222223
[68.         64.33333333 60.33333333]


In [36]:
print(np.std(arr7))
print(np.std(arr7, axis=1))

22.6459600408735
[30.91206165 11.78511302 16.57977349]


In [37]:
# Trigonometric function
np.sin(arr7)

array([[-0.98514626,  0.73319032,  0.99060736],
       [ 0.96836446,  0.99287265,  0.96836446],
       [ 0.12357312,  0.67022918,  0.73319032]])

In [38]:
arr8 = np.arange(12).reshape(3,4)
arr9 = np.arange(12,24).reshape(4,3)

print(arr8)
print("\n")
print(arr9)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [39]:
# dot product
print(np.dot(arr8, arr9))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [41]:
# log and exponents
print(np.exp(arr8))
print("\n")
print(np.log(arr8))
print("\n")

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]




/tmp/ipykernel_7730/282800293.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr8))


In [42]:
# round / floor /ceil
np.round(np.random.random((2,3))*100)

array([[18.,  5., 26.],
       [ 7., 45., 74.]])

| Function  | Meaning                       | Example (`4.7`) | Example (`4.2`) |
| --------- | ----------------------------- | --------------- | --------------- |
| `round()` | Rounds to the nearest integer | `5`             | `4`             |
| `floor()` | Always rounds **down**        | `4`             | `4`             |
| `ceil()`  | Always rounds **up**          | `5`             | `5`             |


In [43]:
np.floor(np.random.random((2,3))*100)

array([[54., 22., 31.],
       [63., 19., 18.]])

In [45]:
np.ceil(np.random.random((2,3))*100)

array([[69., 98., 21.],
       [20., 32.,  6.]])

### Indexing And Slicing

In [46]:
array1 = np.arange(10)
array2 = np.arange(12).reshape(3,4)
array3 = np.arange(8).reshape(2,2,2)

In [48]:
# 1D Array
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
array1[-1]

np.int64(9)

In [64]:
array1[1:5]

array([1, 2, 3, 4])

In [53]:
# 2D Array
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
array2[1,2]    # array2[1][2]

np.int64(6)

In [72]:
array2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [78]:
array2[0::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [82]:
array2[1:2, 0::3]

array([[4, 7]])

In [63]:
array2[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [69]:
array2[0,:]

array([0, 1, 2, 3])

In [65]:
array2[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [84]:
# 3D Array
array3 = np.arange(27).reshape(3,3,3)
print(array3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [85]:
array3[1,0,1]

np.int64(10)

In [86]:
array3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [87]:
array3[0:1, 0:2, 0:2]

array([[[0, 1],
        [3, 4]]])

In [89]:
array3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
array3[0,1,:]

array([3, 4, 5])

In [93]:
array3[1,:,1]

array([10, 13, 16])

In [94]:
array3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [99]:
array3[::2, ::3, ::2]

array([[[ 0,  2]],

       [[18, 20]]])

### **Iteration**

In [100]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
for i in array1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [102]:
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
for j in array2:
  print(j)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [105]:
for k in np.nditer(array2):
  print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [108]:
array3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
for i in array3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [107]:
for k in np.nditer(array3):
  print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [116]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
array1.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
# Transpose
print(np.transpose(array2))
print()
print(array2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [115]:
array3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
array3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [120]:
# ravel --> converts multi-dimensional array to 1D
array2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
array3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Stacking

In [123]:
array4 = np.arange(12).reshape(3,4)
array5 = np.arange(12,24).reshape(3,4)
print(array4)
print()
print(array5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [124]:
# horizontal stacking
np.hstack((array4, array5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [125]:
# vertical stacking
np.vstack((array4, array5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [129]:
# horizontal splitting
np.hsplit(array4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [133]:
# vertical splitting
np.vsplit(array4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# END